### ISSUE TITLE
Accommodation Screen JSON Spec

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#10]
![accommodation_screen](https://cloud.githubusercontent.com/assets/189939/7004737/9039f05e-dc8d-11e4-9752-cbb62cec96f1.png)

We will need to design the JSON for this above screen, this screen appears only if, the user selects that they require "Accommodation" from #3 screen.

Over here we have the following fields
1. Accommodation Type (Spinner) - The values need to come from the server for now the values are 
   - Room
   - Bed
   - Tent
   
   These values need to be available via a **GET** , which if fails (like due to connectivity loss) will be populated by a default set which will be cached locally in the phone.
2. Start Date (for the Accommodation) - Date field of the format **dd-MM-yyyy**
3. Number of Days (to book the Accommodation for from the Start date) - Currently just an integer value
4. Number of Beds: Which is basically the number of people who are coming in for the accommodation.

As usual, when then user presses the "Next" button all of this data will be pushed into the server via a **POST**.

Expected date of completion: **2015-04-09**

**Comment by raghavneesh** [comment]
A post request on Url 
http://localhost:3000/users/accommodation
with the following parameters

type - bed/tent/room
date - dd-mm-yyyy
beds - number [Optional] //1 by default
days - number [Optional] //1 by default

can be used to add and edit the accommodation details for user.

while a GET request on http://localhost:3000/users/accommodation
will give you the accommodation details for the user.

To fetch the types of room just do a GET request on http://localhost:3000/room/types

**Comment by fraggerfox** [comment]
> while a GET request on http://localhost:3000/users/accommodation
> will give you the accommodation details for the user.

No need to pass the user id?

**Comment by raghavneesh** [comment]
For anything related to user, you have to pass the hhtoken.

**Comment by cherrymathew** [comment]
Some further Activity changes are required:
1. The AccomType drop down needs to be a checkbox list now with the following items.
   - Pillow
   - Mat
   - Sleeping Bag
   - Tent
2.  The Accom date field and number of days need to collect info from the previous activity and be a readonly field. This field will be a "start" and "end" date (which I think is easier to implement than "start" and "number of days")
3. A new field which is a checkbox asking if family members arrive. The backend needs to provide a boolean in json
4. A text field (preferrably utf8 friendly, if it's an easy option) so that people can detail any further accoms information like accompanying family info or pointer to other family who are registering separately.

**Comment by raghavneesh** [comment]
I've changed the content-type of request to application/json
Now you can just post the JSON for accommodation request

{
  "hhtoken" : "dNQUZohY59nX480AiR5izeDYxqC0HVirWsgi1hVDvbWMoujgvvUjnfSAo5VVGb",
  "type" : "pillow",
  "description" : "My accommodation description",
  "family" : 1,
  "beds" : 2,
"days" : 3, 
  "date" : "30-05-2015"
}

**Comment by fraggerfox** [comment]
According the re-design of the Accommodation Screen the new JSON for POSTing will be as follows.

```
{
  "hhtoken" : "7x72DpO1twWRRU5uKpGrclMkmsDB8mzJAmF3AObGZFBdeOH52ZQtbl1coNyZi2",
  "tent": "1",
  "sleeping_bag": "0",
  "mat": "0",
  "pillow": "1",
  "family" : "1",
  "family details" : "This will be a string containing names of family members, can optionally be empty."
}
```

The current structure will need to be discarded.

Do let me know when this is implemented.

**Comment by raghavneesh** [comment]
Done. Just replaced the key "family details" with "family_details".

**Comment by fraggerfox** [comment]
Alright, the missing "_" was a typo from my side, thanks for correcting it.

I shall test this and get back to you.

**Comment by fraggerfox** [comment]
Implemented the changes in the latest commit.
