### ISSUE TITLE
Pickup Screen JSON Spec

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#11]
![pickup_screen](https://cloud.githubusercontent.com/assets/189939/7004963/8b9cfb42-dc90-11e4-88a0-bf2f24e187ac.png)

We will need to design the JSON for this above screen, this screen appears only if, the user selects that they require "Pickup" from #3 screen.

Over here we have the following fields
1. Location (Spinner) - The values need to come from the server for now the values are 
   - Location 1
   - Location 2
   - Location 3
   
   These values need to be available via a **GET** , which if fails (like due to connectivity loss) will be populated by a default set which will be cached locally in the phone.
   
   For now I do not have the valid default values list of places, so we can use some filler values which can be changed later on.
2. Arrival Date - Date field of the format **dd-MM-yyyy**
3. Arrival Time - This will be expected time of arrival in **HH:mm** format, which means we will be using _24 Hour_ time format starting from 00:00 to 23:45, the time intervals will only be available in _15 Minute_ intervals, so valid intervals are 00, 15, 30 and 45.
   
   Some Examples
   - Valid Times: _06:15, 14:30, 12:00_
   - Invalid Times: _6:15 AM, 14:20_
4. Number of Seats: Which is basically the number of people who are to be picked up from the location.

As usual, when then user presses the "Next" button all of this data will be pushed into the server via a **POST**.

Expected date of completion: **2015-04-09**

**Comment by fraggerfox** [comment]
@cherrymathew , could you give us a set of valid "Locations" for possible pickup points?

**Comment by cherrymathew** [comment]
> > > > > "fraggerfox" == fraggerfox  notifications@github.com writes:

```
fraggerfox> @cherrymathew , could you give us a set of valid
fraggerfox> "Locations" for possible pickup points?
```

Lower Dharamsala Post Office Bus stop
Dharamsala Bus station
Pathankot Railway station
Kangra Airport (DHM)
Other

I'm thinking that for "Other" it may good to leave a "Notes" section
optionally in that screen. Probably a stretch goal for now.

## 

Cherry

**Comment by fraggerfox** [comment]
> I'm thinking that for "Other" it may good to leave a "Notes" section optionally in that screen. Probably a stretch goal for now.

Agreed, we shall keep it as an improvement option once the basic feature is implemented.

**Comment by raghavneesh** [comment]
You can retrieve the list of locations from the url

http://localhost:3000/locations

Add the pickup with the POST request to URL

http://localhost:3000/users/pickup
{
 date : 'DD-MM-yyyy' [Required],
location : locationValue [Required],
seats : #seats [Optional],
time : Time // as String. Right now there is no check on time
}

Get the pickup of a user with GET request on URL

http://localhost:3000/users/pickup

**Comment by cherrymathew** [comment]
For this screen a few small UI and backend changes are required:
1. The corresponding taxi far to the location of pickup needs to be set (preferrably at the server end).
   eg: Pickup Point: Kangra Airport => Taxi Fare 400Rs
2. When "Next" is pressed a confirmation screen needs to pop-up saying that the user is liable for Taxi fare.

**Comment by raghavneesh** [comment]
Locations now come with "Charge" key in JSON.

**Comment by fraggerfox** [comment]
The strings for the Location query will be returning the following Array

```
{
  "pickup_locations": [
    "Location one\nFare: Rs 120",
    "Location Two\nFare: Rs 220",
    "Location Three\nFare: Rs 300",
    "Location Four\nFare: Rs 400"
  ]
}
```

Do let me know when the changes are done.

The Strings should be configurable at the server end.

**Comment by raghavneesh** [comment]
Don't we want to validate the location value at the backend?

**Comment by fraggerfox** [comment]
I do not think so, it will be entered by the admin

**Comment by raghavneesh** [comment]
Yeah, but when client selects a value, it needs to be validated on backend, right?

**Comment by fraggerfox** [comment]
What exactly do you want to validate?

**Comment by raghavneesh** [comment]
Ok. Leave it. I wanted to validate it in case of strings, but when Admin
enters the location, then the location will have ids.

Don't you ever want to track the no. of users who are coming from
Dharamsala bus stand?

**Comment by fraggerfox** [comment]
> Don't you ever want to track the no. of users who are coming from
> Dharamsala bus stand?

Well I have not implemented any location based tracking in the android application.

**Comment by fraggerfox** [comment]
> Don't we want to validate the location value at the backend?

I been thinking about this, once thing we can do (not exactly validation) is to have the string split into two parts and be stored in the server end separately. For example consider the following location

`Location one\nFare: Rs 120` which comes via JSON. 

Will be stored in the server as `Location One` and `Rs 120` separately in the database. and when I request the locations via "change" key you will generate the string `Location one\nFare: Rs 120` on the fly and then put it in the JSON Response.

This will help the admin of the the server filter locations or prices seperately without much hassle when you are building the UI for it.

What are your thoughts on this?

**Comment by cherrymathew** [comment]
@fraggerfox : If the effort required to have separate numerical keys (including testing, etc.) is not significant, there's value in retaining the numeric semantic (instead of having to parse the Location string each time for fare info). What's the exact problem with having separate keys ? Is the data tracking more complex ?

**Comment by fraggerfox** [comment]
> What's the exact problem with having separate keys ? Is the data tracking more complex ?

As far as the client side is concerned there is no point in trying to separate the strings, in server side it makes sense since "location" and "price" may be used as a filter mechanism.

**Comment by cherrymathew** [comment]
Ok. In its current avatar (given that we have a hand full of locations), I would then say keeping the app simple is important and thus if having a simple string for the drop down is easier, then let's go with that. In the general case, I don't think this is a good idea though.

**Comment by fraggerfox** [comment]
@cherrymathew 

> Ok. In its current avatar (given that we have a hand full of locations), I would then say keeping the app simple is important and thus if having a simple string for the drop down is easier, then let's go with that. In the general case, I don't think this is a good idea though.

I do not think you know what you are talking about, currently, in the hh-appserver, the Locations is defined as a set of JSON Objects of the form in the `appconf.js` file.

```
        "locations" : [{
            "name" : "Dharamsala Bus stand",
            "value" : "dbus",
            "charge" : 250
        },{
            "name" : "Macleod Gunj",
            "value" : "mcleod",
            "charge" : 350
        },{
            "name" : "Pathankot Railway Station",
            "value" : "ptkt",
            "charge" : 1000
        }]
```

All I was is, when the strings are generated for the android device it should be like 

`Dharamsala Bus stand\n Fare Rs: 250` , which is nothing but the concatenation of values as they server generates the strings from it's end when I ask for it to give me a list of locations.

When the POST from the application goes to the server, it will not splitting the string into `Dharamsala Bus stand` and `250` , therefore it would be good to split it up when the response is received at the server end into the above mention values and store them in the database so that it can be used in a more practical way to do filtering if we ever plan to build an administration UI for this.

I hope this brings in more clarity to your original question of the problem of having separate keys.

**Comment by cherrymathew** [comment]
Thanks for the detailed description. From it, what I understand is that the client sends the information concatenated (eg: "Dharamsala Bus stand : 250") but you expect the server to parse that string, split it up into .name and .charge values and store them. Is that a reasonable description of the the situation ?

**Comment by fraggerfox** [comment]
> Thanks for the detailed description. From it, what I understand is that the client (using the api above) sends the information concatenated (eg: "Dharamsala Bus stand : 250") but you expect the server to parse that string, split it up into .name and .charge values and store them. Is that a reasonable description of the the situation ?

@cherrymathew : Yes pretty much, currently the model defined in `Pickup.js` does not split the location and the fare, it just stores it as a single concatenated string like you mentioned in the above example.

@raghavneesh 
1. I do not need a validation to be done for the location, since the user selects it from  a restricted dropdown list, so only values that are provided by us will ever show up in the list. Which makes validation redundant in this scenario.
2. I took the liberty to write up the code to split the incoming string so that only the "location" value is stored in the `Pickup.js` model. The "fare" part is cut out from the string.
3. You can write up the necessary changes needed to implement storing the "fare" in the `Pickup.js` model when you get time, this is not a high priority task at the moment, but would be something good to have.

I have made the following patch to make the server work according to the above mentioned requirements.

```
diff --git a/routes/users.js b/routes/users.js
index 5555740..afab81d 100644
--- a/routes/users.js
+++ b/routes/users.js
@@ -254,7 +254,7 @@ router.get('/accommodation',global.isAuthenticated,function(req, res){
 });

 router.post('/pickup',global.isAuthenticated,function(req, res){
-   if(!req.body.date || !utilities.isValidDate(req.body.date, 'DD-MM-yyyy') || !Pickup.isValidLocation(req.body.location)){
+   if(!req.body.date || !utilities.isValidDate(req.body.date, 'DD-MM-yyyy')){
        res.status(400);
        return res.json({
            error : 'Invalid request'
@@ -264,6 +264,7 @@ router.post('/pickup',global.isAuthenticated,function(req, res){
    Pickup.findOne({
        user : user._id
    },function(error, pickup){
+           var location_string = "";
        if(error){
            return next(error);
        }
@@ -272,7 +273,8 @@ router.post('/pickup',global.isAuthenticated,function(req, res){
        pickup.date = moment(req.body.date, 'DD-MM-yyyy').valueOf();
        pickup.time = req.body.time;
        pickup.seats = parseInt(req.body.seats || '1', 10);
-       pickup.location = req.body.location;
+           location_string = req.body.location.toString().split("\n");
+       pickup.location = location_string[0];
        pickup.user = user._id;
        pickup.save();
        return res.json(pickup);
```

Kindly apply this and do let me know when it is done.

**Comment by raghavneesh** [comment]
Don't worry about it too much, because it's going to change when admin
start entering the location, then locations will be in database and the
structure for the location will be
{
_id : ObjectId('objectid'),
name : "Dharamsala Bus stand"
}

Client is supposed to send the ObjectId so that we can create a
relationship between talk and location.
Let me know your thoughts about it.

**Comment by fraggerfox** [comment]
> Client is supposed to send the ObjectId so that we can create a
> relationship between talk and location.
1. We are not have any relationship between talks and location at the moment, the only use of location is to have the people who are responsible for dispatching the Taxi get the necessary information conveyed to the Taxi drivers.
2. I am not using or storing the `ObjectId` of any object present from the server in the client side.

**Comment by raghavneesh** [comment]
Sorry, not talk, it is from any particular entity to another entity, as in
this case with Pickup.
You don't have to store the ObjectId, you'll get the id in location JSON
object, which you'll send back to server
when user select the location instead of some random name string.
Advantage :
We can add any number of unique location in this scenario tracked by their
ids, so that we can always query on our database as
who are the users coming from location having this id. In case of random
String it is always hard to query the database.

**Comment by fraggerfox** [comment]
Using the relationship you have in your models, can you not query the user's pick up location from the possible "fixed" set of strings that you have?

**Comment by raghavneesh** [comment]
In my opinion that would not be the right way, as you always have to
sanitize string for querying and keeping a sanitized string as value/id.

For instance. Location name with special character. You cannot rely on that.

**Comment by fraggerfox** [comment]
> For instance. Location name with special character. You cannot rely on that.

We will probably not be going for a generic implementation at the moment, we will have just a list of known places in Dharamsala, which as you know is mostly alphabets and probably a "space" so do not worry about sanitizing the strings at the moment, we are talking about 3 - 4 pickup points nothing more.

**Comment by fraggerfox** [comment]
Implemented the changes in the latest commit.
