### ISSUE TITLE
hh-appserver <-> Dokuwiki interaction (signup)

### ISSUE THREAD

**Issue by cherrymathew** [raghavneesh/hh-appserver#16]
The template for this requirement is driven by the implementation of
this form:
http://hillhacks.in/signup

We select relevant fields from this form and push them to docuwiki.

The following details regarding people attending are required
to be transferred to the hillhacks docuwiki page in a Key/Value pair
style. The template for generating this will be spec-ed out later.

The Main section should have the following key:value pairs:

Attend Main Conference Events: Yes | No
Attend Pre Conference Events:  Yes | No
Present a talk, workshop or session: Yes | No
Teach in the school outreach sessions: Yes | No
Attend Learn To Code : Yes | No
Mentor at Learn To Code : Yes | No

---

A subsection within the main section should contain the following
key:value pairs:

interestlevel: "Yes I am coming, dates set!"

accommodation: Yes | No
publication: Yes | No
arrival: $DATE-OF-ARRIVAL
departure: $DATE-OF-DEPARTURE

---

PS: The fields may have more constraints, given that people sign up at
the last minute - we'll spec that out later.

**Comment by cherrymathew** [comment]
The signup integration is done (thanks @debanjum ! )

The changes will be integrated on the deployment server along with an integration process.

**Comment by fraggerfox** [comment]
Completed by @debanjum
