### ISSUE TITLE
hh-appserver <-> Dokuwiki interaction (cfp)

### ISSUE THREAD

**Issue by cherrymathew** [raghavneesh/hh-appserver#17]
= $TITLE =

---- dataentry signup ----
type_hidden     : Talk
title           : $TITLE
by              : $NAME
email_hidden    : $EMAIL
other_hidden    : No
othname_hidden  : No
projector_hidden: "Yes, I need it" |
                  "No, I don't need it"
tool_hidden       : "No, I don't need any tools" |
                    "Yes, I need tools"
toolSpec_hidden   : $FREEFORM
else_hidden       : No
duration          : $FREEFORM
abstract_hidden : ""
speaker_hidden  : ""

**Comment by cherrymathew** [comment]
The CFP page creation implementation is done (Thanks @debanjum !) 

This will be deployed on the server as part of an integration process.

**Comment by fraggerfox** [comment]
Completed by @debanjum
