### ISSUE TITLE
Implementing the Welcome Screen

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#2]
This is a high level view of the Welcome screen requirement.

![welcome_screen](https://cloud.githubusercontent.com/assets/189939/6540401/ac40d8be-c4c1-11e4-9412-34efeb2107b9.png)
- As the next step let us try implementing the day selection and
  checkbox on accommodation and transport (ref: screenshot attached)
- For now do not worry about the collection / tables for
  accommodation / transport, we will store the accommodation / transport
  as a boolean field in the User object to see if the User has requested
  the services. Hopefully in the next iteration we will be expanding on
  both the accommodation and transport details (the number, time, type
  etc).
- We will need to keep track of the days the user is visiting,
  currently for this specific application I am just using a boolean
  array of 14 days, marking true / false for the days the user wishes to
  attend and store it in the user object.

**Comment by raghavneesh** [comment]
Can a user book for himself only?
Where would he specify the numbers of people coming?
What would be the flows of edition and addition of booking?

**Comment by fraggerfox** [comment]
> Can a user book for himself only?

For now yes

> Where would he specify the numbers of people coming?
> What would be the flows of edition and addition of booking?

This will be in the second iteration.

**Comment by fraggerfox** [comment]
We will be implementing the the features in the upcoming tickets.

Marking this as closed, since we are done with the basic implementation for now.
