### ISSUE TITLE
Weclome Screen JSON Spec

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#3]
![welcome_screen](https://cloud.githubusercontent.com/assets/189939/6540401/ac40d8be-c4c1-11e4-9412-34efeb2107b9.png)

It would be nice to have the JSON API expected responses / requests. For the welcome screen.

Do let me know if what sort of request JSONs that you expect from the android side so that we can spec out the details.

**Comment by raghavneesh** [comment]
Welcome Screen :

Request : 
  type : 'POST'
   url : '/reservedates',
   parameters : 
      dates : comma separated dates e.g. 25-04-2014, 28-04-2015 or 25-04,28-04 or 25,28
      accommodation : 1 for true & 0 for false,
      pickup : 1 for true & 0 for false
      seats : Number of seats to book //Not implemented yet

Response :  Booking Object

Request : 
   type : 'GET',
   url : '/reservedates'
  Response : Booking Object

**Comment by fraggerfox** [comment]
Is this a GET or a POST?

**Comment by fraggerfox** [comment]
So an example of the a JSON for Request is

``` javascript
{
  "dates": 25-04-2015,28-04-2015,29-04-2015
  "accommodation": "1",
  "pickup": "0",
  "seats": "0"
}
```

Is this correct? 

> dates : comma separated dates e.g. 25-04-2014, 28-04-2015 or 25-04,28-04 or 25,28

Also the dates are just a CSV string. am I correct in assuming that?

> Response : Booking Object

Can you give me an example of the response JSON?

**Comment by raghavneesh** [comment]
Yeah. the provided strings are correct. If you just want to use the month and year of event's start date you can avoid mentioning month and year.

Response Object would be like the following : 

{
    "__v": 1,
    "_id": "54fb14ee9ca0e8a14716c49f",
    "accommodation": true,
    "pickup": true,
    "user": "54f83550a30561ab2a42943b",
    "dates": [
        1429986600000,
        1430073000000
    ]
}

where array has date's timestamps.

**Comment by fraggerfox** [comment]
> "user": "54f83550a30561ab2a42943b",

Is this the user identifier like Phone number / Email etc? or Is this a completely different handle?

**Comment by raghavneesh** [comment]
This is the user id in db. User can later have multiple email ids. We will talk with this user id once user logged in using his email/phone.

**Comment by fraggerfox** [comment]
Alright, thanks, answers most of my questions for now

**Comment by fraggerfox** [comment]
When I tried to post to `/reservedates` I get a 404

`POST /reservedates 404 1ms - 46b`

Also why is no userID sent along with the reserve dates POST.

In other words, how does the user get identified when the JSON comes in.

**Comment by raghavneesh** [comment]
Sorry for the confusion. I moved this router to user in last build. It's /user/reservedates now.

**Comment by fraggerfox** [comment]
I still get a 404, am I doing something wrong?

`POST /user/reservedates 404 4ms - 46b`

**Comment by raghavneesh** [comment]
Working for me. You're requesting from which client?

**Comment by fraggerfox** [comment]
From android

**Comment by fraggerfox** [comment]
This is my request JSON

```
{
  "pickup": "0",
  "date": "23-5-2015,24-5-2015,25-5-2015,26-5-2015",
  "seats": "0",
  "accomodation": "1"
}
```

When I make this post, how does server identify which user is trying to update their pick up / booking and accommodation.

**Comment by raghavneesh** [comment]
If it is still giving 404, then try requesting from Postman and let me know whether it works or not.

To make this request user needs to get loggedin to the system and if he's loggedin we can always get him from the session.

**Comment by fraggerfox** [comment]
> To make this request user needs to get loggedin to the system and if he's loggedin we can always get him from the session.
- How is the user session maintained? 
- And as an android client how can I see the status of the user session? Is there an API call to do this

Currently the client system works like this
- Once the user registers the User Object (in android) is retained and the user identifier handle (email / phone) is used for doing transactions to the server.
- So each transaction as far as the android is concerned is atomic and there are no states stored in the android side regarding if the server is keeping track of the user or not.

**Comment by raghavneesh** [comment]
Session is maintained through cookies.  You need to get cookies from response header and store them somewhere.
Send back the cookies to server with each request, like browser does.
Check the code I gave you.

**Comment by fraggerfox** [comment]
![restclient_response](https://cloud.githubusercontent.com/assets/189939/6555105/b318a78e-c688-11e4-9d33-50d085f36c75.png)

This is what I get when I do a direct post using RESTClient

**Comment by raghavneesh** [comment]
![screenshot from 2015-03-09 18 20 05](https://cloud.githubusercontent.com/assets/2082996/6555138/19737f04-c689-11e4-8999-c22cdc36c855.png)

I'm getting this.

**Comment by raghavneesh** [comment]
Can you try one thing?

In your browser window hit http://localhost:3000/users

Let me know, what it says

**Comment by fraggerfox** [comment]
> Session is maintained through cookies. You need to get cookies from response header and store them somewhere.
> Send back the cookies to server with each request, like browser does.
> Check the code I gave you.

Sessions on server side based on cookies is fine, but I do not want to maintain or store cookies on the android client, I rather have a token that is generated from the server side and thrown between the client and server via JSON for identifying the user for which the various transactions are happening. 

I would like to avoid using any HTTP specific features (cookies, headers, sessions) etc and make the application solely rely on JSON for all it's needs, since a RESTful API should not depend on the protocol specific features to get it's job done.

The token thrown around can be the cookie which is maintained on the server side but this should show up in the JSON that is exchanged between the server and client. So for example after authentication you can have a  `"cookie" : "some_cookie_value"` in the JSON that we can exchange as we communicate. In this specific case of booking it will look like this.

```
{
  "pickup": "0",
  "date": "23-5-2015,24-5-2015,25-5-2015,26-5-2015",
  "seats": "0",
  "accomodation": "1",
  "cookie": "some_cookie_value"
}
```

**Comment by fraggerfox** [comment]
> In your browser window hit http://localhost:3000/users
>   Let me know, what it says

`{"error":"User not logged in"}`

**Comment by raghavneesh** [comment]
With android it is the same thing. If you don't want Android to handle, just set the cookieStore to false. You will have to just parse the "remember_me" cookie from header which is the token, and store it on client. Later send it with each request.
If we're sure we want to do this I'll need to change some code around.

**Comment by cherrymathew** [comment]
> > > > > "Avneesh" == Avneesh Raghav notifications@github.com writes:

```
Avneesh> With android it is the same thing. If you don't want
Avneesh> Android to handle, just set the cookieStore to false. You
Avneesh> will have to just parse the "remember_me" cookie from
Avneesh> header which is the token, and store it on client. Later
Avneesh> send it with each request.  If we're sure we want to do
Avneesh> this I'll need to change some code around.
```

I think what fraggerfox is saying is that:
- The "cookie" is an HTTP protocol specific construct, which breaks
  abstraction both from the client implementation side, and from a
  network protocol PoV.
- Implementing browser cookie functionality may be unwise, since it is
  beyond the scope of the application.
- If the server can abstract the http cookie mechanism within a JSON
  api, it would be acceptable, given the above.

## Hope that makes sense.

Cherry

**Comment by raghavneesh** [comment]
Ok.. You continue with the current dummy responses. I'll implement it asap.

**Comment by raghavneesh** [comment]
The response of the /verify request has now been changed to 
{
  hhtoken : "token",
  user : userObject
}

You'll have to now include "hhtoken" as a parameter in every request to authenticate. The backend server does not keep any state and authenticate user based on token, which has an expire time of 8 days since last access.

Have not tested the flow much yet. Please test it thoroughly.

**Comment by fraggerfox** [comment]
How do I get the value of this token? Could you give me a detailed example JSON response.

**Comment by raghavneesh** [comment]
So, when you verify/login a user using a code which is sent to his mobile/email, you'll get the token in response under the token key.  
For instance > 
{
    "hhtoken": "QrTSoXZmknIKpyrnZt6J9a9qaHS62HqlOWEDwrBADBvHGJo1K96w7uWGDbr86r",
    "user": {
        "__v": 0,
        "_id": "54f83550a30561ab2a42943b",
        "created_at": 1425552720591,
        "email": "avneesh.raghav@instaenroll.com",
        "isVerified": true,
        "last_login": 1426054009321
    }
}

**Comment by fraggerfox** [comment]
Understood, I shall work on it and get back to you

**Comment by fraggerfox** [comment]
I was able to extract and store the token in the User Object in Android side, so for reserving dates do I just do a post in `/user/reservedates` with the following JSON for example

```
{ 
  "hhtoken" : "7x72DpO1twWRRU5uKpGrclMkmsDB8mzJAmF3AObGZFBdeOH52ZQtbl1coNyZi2",
  "pickup": "0",
  "date": "23-5-2015,24-5-2015,25-5-2015,26-5-2015",
  "seats": "0",
  "accommodation": "1",
}
```

**Comment by raghavneesh** [comment]
Exactly.

**Comment by fraggerfox** [comment]
After posting the below mentioned request 

```
{
  "seats" : "0",
  "pickup" : "0",
  "date" : "23-5-2015,24-5-2015",
  "accommodation" : "1",
  "hhtoken" : "9l4fKsKaf1b9qeKuDiOHKv6GTmMyRi1n5oCXxRZf7Q18N4tNZUAeLLYNERxpJ7"
}
```

I still get a 404

```
{
  "error" : {
    "status" : 404
  },
  "message" : "Not Found"
}
```

Is there anything I am missing out?

**Comment by raghavneesh** [comment]
Do you have teamviewer?

**Comment by fraggerfox** [comment]
No I do not and I do not wish to install it either.

**Comment by fraggerfox** [comment]
Is there like a debug log that you generate from the server end? Which I could send back.

**Comment by raghavneesh** [comment]
404 would not have any log. It simply not finding the route somehow..

**Comment by raghavneesh** [comment]
Can you send me the exact URL with parameters?

**Comment by fraggerfox** [comment]
`http://127.0.0.1:3000/user/reservedates`

That is the exact URL I am trying to access, there are no parameters only the JSON which is send via POST.

**Comment by fraggerfox** [comment]
Interestingly, If I send a malformed JSON it does not say 404

```
{
  "error" : {
    "body" : "{\n  \"seats\" : \"0\",\n  \"pickup\" : \"0\",\n  \"date\" : \"23-5-2015,24-5-2015\",\n  \"accommodation\" : \"1\",\n  \"hhtoken\" : \"uVDJY5IugSzxinZ7dwho48lcHh0DR4NBpMpYbsBC4qe7rTyg2i3nJBV8O4JUXH\",\n}",
    "status" : 400
  },
  "message" : "Unexpected token }"
}
```

It is Bad Request 400, which means it is finding the route correct?

**Comment by raghavneesh** [comment]
That might be because the request is handled by the middleware first and then move to the exact route.

**Comment by fraggerfox** [comment]
Understood

**Comment by fraggerfox** [comment]
Alright, I found the issue the router path is `/users/reservedates` and not `/user/reservedates` (Note the missing "s"), anyway now I am getting a 

```
{
  "error" : "Invalid request"
}
```

When I do a POST and I traced it to 

```
    if(!eventDates || !eventDates.length){
        res.status(400);
        return res.json({
            error : 'Invalid request'
        });
    }
```

in `routes/users.js` 

The POSTed JSON is

```
{
  "seats" : "0",
  "pickup" : "0",
  "date" : "23-5-2015,24-5-2015",
  "accommodation" : "1",
  "hhtoken" : "JGXv931eUgQn4hqycPwiuJSAz5CQ907LQWK6GHLEPvYhWtlAeGPfszM7LcrDG4"
}
```

What do you think is causing the issue? Is it some issue with the JSON?

**Comment by raghavneesh** [comment]
Can you check with dates in conf/appconf.js.

There is a validation that you cannot enter date before or after the event.

**Comment by fraggerfox** [comment]
```
        "startDate" : new Date("2015-05-20").getTime(),
        "endDate" : new Date("2015-06-08").getTime()
```

I set these as the start / end dates and I am still getting the error.

**Comment by raghavneesh** [comment]
While posting month can you keep it 1 less as date in javascript starts with 0 . I'll handle it asap.

**Comment by fraggerfox** [comment]
After some debugging I was able to figure out how the server works, and I was able to complete the transactions

**Comment by fraggerfox** [comment]
Due to the change in requirements, we have re-structured the JSON, the new JSON for POSTing a attending dates will be like below

```
{ 
  "hhtoken" : "7x72DpO1twWRRU5uKpGrclMkmsDB8mzJAmF3AObGZFBdeOH52ZQtbl1coNyZi2",
  "arrival_date": "23-05-2015",
  "departure_date": "01-06-2015",
  "pickup": "0",
  "accommodation": "1",
  "talk": "1"
}
```

Do let me know when the changes done.

**Comment by raghavneesh** [comment]
If this is JSON you may not want to send 0 and 1 as string.

**Comment by raghavneesh** [comment]
Done. Just don't send the integers as String.

**Comment by fraggerfox** [comment]
Alright, will put it as numbers, thanks for making the changes. I shall test it out and get back to you.

**Comment by fraggerfox** [comment]
Implemented the changes in the latest commit.
