### ISSUE TITLE
Talk Screen JSON Spec

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#5]
![talkscreen](https://cloud.githubusercontent.com/assets/189939/6738158/213d7a7c-ce96-11e4-86f9-f3e6e23cdd59.png)

The details of the various JSON API expected from the Talk Screen

**Comment by raghavneesh** [comment]
Talk Screen CRUD Operations : 

> **Create** 

**url** : /users/talk/add
**type** : POST
**parameters** : 
            title : String title
            description : String title
            datetime : DD-MM-YYYY HH:mm
            duration : String (130 min or 2:30) //No validation for now
            type : String for any type (workshop || talk || classroom)
            location : String for location (name~latitude~longitude) where latitude and longitude are optional

**Response**
{
    "__v": 0,
    "_id": "54fb4861ceaa0cef6aecbcb5",
    "created_at": 1425754209558,
    "date": 1432548000000,
    "description": "something something",
    "duration": "230min",
    "title": "My edited talk",
    "type": "talk",
    "updated_at": 1425754246617,
    "user": "54fb353cddeba131533d834c",
    "location": {
        "name": "rampur",
        "lat": 230.5,
        "lng": 560.3
    }
}

> **Edit** 

**url** : /users/talk/edit/54fb4861ceaa0cef6aecbcb5
**type** : POST
**parameters** : 
    Same as add
**Response**
   Same as add

> **Retrieve** 

**url** : /users/talk/54fb4861ceaa0cef6aecbcb5
**type** : GET
**Response**
 Same as add

> **Delete** 

**url** : /users/talk/delete/54fb4861ceaa0cef6aecbcb5
**type** : GET
**Response**
 {
   "deleted" : true
}

**Comment by fraggerfox** [comment]
> type : String for any type (workshop || talk || classroom)
> location : String for location (name~latitude~longitude) where latitude and longitude are optional

Type and Location values, will this come for the server side? As in can I fetch the various types like Workshop / Talk / Classroom etc by using an URL and then populate it in the android client?

**Comment by cherrymathew** [comment]
> > > > > "fraggerfox" == fraggerfox  notifications@github.com writes:

```
fraggerfox>     type : String for any type (workshop || talk ||
fraggerfox> classroom) location : String for location
fraggerfox> (name~latitude~longitude) where latitude and longitude
fraggerfox> are optional

fraggerfox> Type and Location values, will this come for the server
fraggerfox> side? As in can I fetch the various types like Workshop
fraggerfox> / Talk / Classroom etc by using an URL and then populate
fraggerfox> it in the android client?
```

Yes, because the admin needs to be able to update this at will.

## 

Cherry

**Comment by raghavneesh** [comment]
Talk types are available at the following route : 
http://localhost:3000/talk/types

The response will be the list of types as follows : 

['workshop', 'talk', 'event']

We can set the names for the values on Client or if you want the name from the backend we can do so.

**Comment by fraggerfox** [comment]
After discussion with @cherrymathew we have decided to sent only the Talk "title" and "date" for now since we do not collect any other data from the user at this point in time.

Is it possible for you to modify the server so that it can take a JSON request like

```
{
  "talks" : [
    {
      "title" : "Some Title 1",
      "date" : "2015-05-23"
    },
    {
      "title" : "Some Title 2",
      "date" : "2015-05-24"
    }
  ],
  "hhtoken" : "diIfbxEhdgOxL1OkG1GhWzjNnuKVrUyxF20EfVYqxbOQZfUd5uqM8pWreQOpto"
}
```

to register the talks for an user?

**Comment by raghavneesh** [comment]
Are we taking entries of multiple talks now?

**Comment by fraggerfox** [comment]
Yes.

**Comment by raghavneesh** [comment]
Done. Now it accept two parameters in request body.
1. hhtoken
2. talks : [
    {
      "title" : "Some Title 1",
      "datetime" : "2015-05-23"
    },
    {
      "title" : "Some Title 2",
      "datetime" : "2015-05-24"
    }
  ]

You can also specify time with dates. The format is YYYY-MM-DD HH:mm

In case of error, response of that particular talk with contain 'error' key.

**Comment by fraggerfox** [comment]
One question, I should do this POST in `/users/talk/add` correct?

**Comment by raghavneesh** [comment]
Right.

**Comment by fraggerfox** [comment]
I posted the following JSON

```
{
  "hhtoken" : "YsfsIMEzjupNdjVrg9gD4cCXJvJHAS8tP3tUX8XUH4Eg9tZ30gdqmEgdK0ql91",
  "talks" : [
    {
      "title" : "Some Title 1",
      "datetime" : "2015-05-23"
    },
    {
      "title" : "Some Title 2",
      "datetime" : "2015-05-24"
    }
  ]
}
```

I got a HTTP 500, Internal Server Error with the following JSON

```
{
  "error" : "Invalid talks request json"
}
```

The token is a valid token, is there something I am doing wrong in the request body?

**Comment by raghavneesh** [comment]
Working for me.. Can you put "console.log(err)" in line number 99 in
users.js and restart the server.

Then try and check in console for error.

**Comment by fraggerfox** [comment]
Alright let me try. I shall get back to you.

**Comment by fraggerfox** [comment]
```
[SyntaxError: Unexpected token o]
POST /users/talk/add 500 56ms - 38b
```

I get this message in the node.js console. I hope this helps.

**Comment by fraggerfox** [comment]
Ayush helped me a bit with debugging the code and found out the issue was the `JSON.parse(...)` function. 

```
index 16d5819..a71e7e3 100644
--- a/routes/users.js
+++ b/routes/users.js
@@ -67,7 +67,7 @@ router.get('/reservedates',global.isAuthenticated, function(re
q, res){
 router.post('/talk/add', global.isAuthenticated, function(req, res){
        if(req.body.talks){
                try{
-                       var talks = JSON.parse(req.body.talks),
+                       var talks = req.body.talks,
                        userId = req.user._id;
                        if(!talks.length || !talks.splice){
                                throw 500;
```

The incoming `req.body.talks` is already an object and not a string, hence `[SyntaxError: Unexpected token o]` where "o" stands for "object", once the change was made I got the following response.

```
[
  {
    "__v" : 0,
    "user" : "550040c002bed9282934333b",
    "created_at" : 1427185730730,
    "date" : 1432319400000,
    "title" : "Some Title 1",
    "_id" : "55112042469d68e8325b7034"
  },
  {
    "__v" : 0,
    "user" : "550040c002bed9282934333b",
    "created_at" : 1427185731078,
    "date" : 1432405800000,
    "title" : "Some Title 2",
    "_id" : "55112043469d68e8325b7035"
  }
]
```

**Comment by fraggerfox** [comment]
I shall keep you updated on the progress here.

**Comment by raghavneesh** [comment]
Ok. Then it might the issue with node or express version because I get the
body in String.

**Comment by raghavneesh** [comment]
*Before Parsing : *
[     {       "title" : "Some Title 1",       "datetime" : "2015-05-23"
},     {       "title" : "Some Title 2",       "datetime" : "2015-05-24"
  }   ]

_After Parsing :_

[ { title: 'Some Title 1', datetime: '2015-05-23' },
  { title: 'Some Title 2', datetime: '2015-05-24' } ]

**Comment by fraggerfox** [comment]
You are testing the server with Postman - Rest Client correct? What is the value of the "Content-Type" you are passing in?

**Comment by fraggerfox** [comment]
In addition to this I have been trying to understand how the GET works in getting the existing talks (if any) for a given user

I tried to do a GET on `/users/talk/550040c002bed9282934333b` and got the following response (the value passed is a valid id from the database)

```
{
  "error" : "Talk not found"
}
```

How do I pass the `hhtoken` in this URL to verify the user before doing a GET? Also is it possible to pass the user identifier in the URL along with the `hhtoken` instead of the mongodb id to get the list of talks.

For example I tried to get the talks using the following url `/users/talk/john%40example.com` and I got the following response

```
{
  "error" : {
    "message" : "Cast to ObjectId failed for value \"john@example.com\" at path \"_id\"",
    "name" : "CastError",
    "type" : "ObjectId",
    "value" : "john@example.com",
    "path" : "_id"
  }
}
```

**Comment by raghavneesh** [comment]
Ok.. I'm using form encoded

application/x-www-form-urlencoded

**Comment by fraggerfox** [comment]
`application/x-www-form-urlencoded`

It should be set to `application/json` when you are testing JSON based web applications, this is according the [RFC 4627](http://www.ietf.org/rfc/rfc4627.txt) document, Page 5, Section 6

> The MIME media type for JSON text is application/json.

**Comment by fraggerfox** [comment]
I had raised a question on how to retrieve user talks here https://github.com/raghavneesh/hh-appserver/issues/5#issuecomment-85499673

Can you give me a clarification on this question?

Also I still see the code for parsing the JSON body has not changed, the bug described here https://github.com/raghavneesh/hh-appserver/issues/5#issuecomment-85405238 still exists.

**Comment by raghavneesh** [comment]
This request doesn't need the hhtoken. I've kept this open in case we want to show the talks without user login.
Right now I've not handled the case for request without proper ObjectId. Will show a readable error in case of invalid ObjectId.

**Comment by cherrymathew** [comment]
Final reqs update after our call tonight:
1. Remove the "date" of talk ( or the app shouldn't use it)
2. A "type" of talk field is required with the following mutually exclusive options for a drop down list:
   - Talk
   - Workshop
   - Session
3. An "event" field is required with the following mutually exclusive options for a drop down list:
   - Code Camp
   - School Program
   - Unconference
   - Main Conference
4. A _TEXT_ field called "Duration/Requirements" so speakers can add further info about the talk and any equipment/venue requests (PA system, projector, etc. etc. but it's free form text we don't structure it ).

**Comment by raghavneesh** [comment]
Done.
Now you can post talk JSON as follows : 
{
 "talks" : [{
 "title" : "title",
 "type": "type",
"event" : "event",
"description" : "description",
"requirements" : "requirements"
}]
}

You can fetch events from 
http://localhost:3000/talks/events

**Comment by fraggerfox** [comment]
The following is an example of how the new Talks page JSON will be generated.

```
{
  "talks" : [
    {
      "title" : "Some Title 1",
      "type" : "Workshop",
      "event" : "CodeCamp",
      "duration" : "2 hours"
      "hasCoPresenters" : 0,
      "needsProjector" : 1,
      "needsTools" : 0,
      "notes" : "Some note regarding talk 1"
    },
    {
      "title" : "Some Title 2",
      "type" : "Talk",
      "event" : "Main Conference",
      "duration" : "1 week"
      "hasCoPresenters" : 1,
      "needsProjector" : 1,
      "needsTools" : 0,
      "notes" : "Some note regarding talk 2"
    }
  ],
  "hhtoken" : "diIfbxEhdgOxL1OkG1GhWzjNnuKVrUyxF20EfVYqxbOQZfUd5uqM8pWreQOpto"
}
```

Let me know when the changes are implemented.

**Comment by fraggerfox** [comment]
Any updates on this @raghavneesh ?

**Comment by raghavneesh** [comment]
Will do it by tomorrow morning.

**Comment by fraggerfox** [comment]
Alright, thanks

**Comment by raghavneesh** [comment]
Done..

**Comment by fraggerfox** [comment]
Alright, I shall check it out and work on the implementation.

**Comment by fraggerfox** [comment]
Once again we do not need to validate the Events or Types because they come from a restricted set very much like locations mentioned in #11 , I wrote a patch removing the validation part from the `Talks.js` model.

```
diff --git a/models/Talk.js b/models/Talk.js
index c0715b8..7e0705e 100644
--- a/models/Talk.js
+++ b/models/Talk.js
@@ -34,16 +34,8 @@ Talk.methods.saveTalk = function(talkInfo,userId,done){
    if(talkInfo.title)
        _this.title = talkInfo.title;
    _this.notes = talkInfo.notes;
-
-   if(Talk.statics.isValidType(talkInfo.type))
-       _this.type = talkInfo.type;
-   else if(talkInfo.type)
-       return done('Not a valid Talk Type');
-   if(Talk.statics.isValidEvent(talkInfo.event))
-       _this.event = talkInfo.event;
-   else if(talkInfo.event)
-       return done('Not a valid Talk event');
-
+   _this.type = talkInfo.type; 
+   _this.event = talkInfo.event;
    _this.duration = talkInfo.duration;
    _this.hasCoPresenters = !!talkInfo.hasCoPresenters;
    _this.needsProjector = !!talkInfo.needsProjector;
@@ -83,4 +75,4 @@ Talk.statics.isValidEvent = function(eventType){
    return (global.Event.talk.events.indexOf(eventType) > -1);
 }

-module.exports = mongoose.model('talks',Talk);
\ No newline at end of file
+module.exports = mongoose.model('talks',Talk);
```

**Comment by fraggerfox** [comment]
Implemented the changes in the latest commit.
