### ISSUE TITLE
Allow proper user verification through Phone numbers

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#6]
Currently if a user tries to verify by Phone it gets rejected, the regular expression does not allow certain patterns due to the limitation of the 10 digits for a phone number check in the current one. 

Preferably a regex like `[+0](0)?\d{10}[\d]*` would be nice to allow for some flexibility especially when numbers are international or has country code

Example matches

09876543210
+916789875671
+9128907896781

P.S: I have not hard tested the regex so do verify it before applying.

**Comment by raghavneesh** [comment]
Kept the country code necessary. The following formats would work

+XX-XXXX-XXXX
+XX.XXXX.XXXX
+XX XXXX XXXX

**Comment by fraggerfox** [comment]
Country code should be optional, people registering from within India may not use country code and would just prefix a "0"

**Comment by raghavneesh** [comment]
It's optional now. The following formats would work

+XX-XXXXXXXXXX
+XXXXXXXXXXXX
0XXXXXXXXX
XXXXXXXX

**Comment by fraggerfox** [comment]
I gave a number `+919447501514` but when I try to verify with the correct verification code and did a GET on the following URL `verify?identifier=+919447501514&code=691638` I get the following response

```
{
  "error" : "Invalid request"
}
```

**Comment by raghavneesh** [comment]
Because of the special significance of '+' in url, you need to decode the parameters before sending them to server. In this case it would work if you send the phone number as "%2B919447501514"

**Comment by cherrymathew** [comment]
> > > > > "Avneesh" == Avneesh Raghav notifications@github.com writes:

```
Avneesh> Because of the special significance of '+' in url, you need
```

Shouldn't this be handled inside json ? Or is url encoding a thing
inside json strings as well ? (I'd be suprised if!)

## 

Cherry

**Comment by raghavneesh** [comment]
We're not dealing with JSON in this case. It's just a simple GET request. If we want to change it to JSON then we can do that. Or then it would be great to change all the requests to JSON format only.

**Comment by fraggerfox** [comment]
How is it that when I use `verify?identifier=john@example.com&code=691638` I get the following response (which is the expected response.)

```
{
  "error" : "Code did not match."
}
```

I do not URL encode "@" to "%40" yet the data is parsed correctly.

**Comment by raghavneesh** [comment]
This is because in encoded url spaces are converted to '+', hence, when
server is decoding your '+' with number it is converting in to a space,
which is not the case with above example.

**Comment by fraggerfox** [comment]
I was not aware that encoded URL spaces are converted to a "+", I know that "+" was used as a filler to create URLs if there were spaces in a string, for example the string `hello world` gets encoded as `hello%20world` if properly encoded, the space gets encoded as `%20` 

But I have changed the code in android to do explicit URL encoding, so that should take care of the issue now.

Closing the ticket since it has been resolved.
