### ISSUE TITLE
The EvenD workflow

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#7]
Here is the basic backend implementation that we need by 23rd March
- Login Screen (Done)
- Welcome Screen (Done)
- Accommodation Screen (Done)
- Pickup Screen (Done)
- Talks Screen (Done)

Once the basic workflow is done, we will work on the expansions on each of the functionality.

**Comment by raghavneesh** [comment]
What are the things pending on Login Screen and Talks screen?

**Comment by fraggerfox** [comment]
The SMS gateway, which needs to be implemented in the future.

**Comment by fraggerfox** [comment]
Added the new screens that needs to be done, will be creating tickets for each with details.

**Comment by fraggerfox** [comment]
Updated the status of Accommodation Scree  as Done

**Comment by fraggerfox** [comment]
Updated the status of Pickup and Talks Screen as Done

**Comment by fraggerfox** [comment]
Closing ticket since the task is completed.
