### ISSUE TITLE
Server crashes on token expiry check

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#8]
I got error then when I accessed the welcome screen after the recent pull.

Here is the stack trace

```
/home/fox/dev/node/hh-appserver/models/Token.js:37
                if(token.isExpired()){
                        ^
TypeError: Cannot read property 'isExpired' of null
    at Promise.<anonymous> (/home/fox/dev/node/hh-appserver/models/Token.js:37
:11)
    at Promise.<anonymous> (/home/fox/dev/node/hh-appserver/node_modules/mongo
ose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/home/fox/dev/node/hh-appserver/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/fox/dev/node/hh-appserver/node_modules/mongoose/
node_modules/mpromise/lib/promise.js:97:20)
    at Immediate.cb (/home/fox/dev/node/hh-appserver/node_modules/mongoose/lib
/query.js:1150:30)
    at Immediate._onImmediate (/home/fox/dev/node/hh-appserver/node_modules/mo
ngoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by raghavneesh** [comment]
Can you check whether you have that token in your database?

db.tokens.findOne({token : "bXLCaLAojXlaLOX0OHaCnme73jXki6nmkFO2NyDixu3Y67TpqFmX2fGMEcNN2l"})

I'll add this case in code.

**Comment by fraggerfox** [comment]
```
 > db.tokens.findOne({token : "bXLCaLAojXlaLOX0OHaCnme73jXki6nmkFO2NyDixu3Y67TpqF
mX2fGMEcNN2l"})
null 
```

Here is the result from querying mongodb.

**Comment by raghavneesh** [comment]
Sorry.. Use your own token in value.

**Comment by fraggerfox** [comment]
```
> db.tokens.findOne({token : "YsfsIMEzjupNdjVrg9gD4cCXJvJHAS8tP3tUX8XUH4Eg9tZ30g
dqmEgdK0ql91"})
{
        "_id" : ObjectId("550fb775a5f7e1741c5817cf"),
        "created_at" : 1427093365137,
        "accessed_at" : 1427100525161,
        "uid" : "550040c002bed9282934333b",
        "token" : "YsfsIMEzjupNdjVrg9gD4cCXJvJHAS8tP3tUX8XUH4Eg9tZ30gdqmEgdK0ql9
1",
        "__v" : 0
}
```

I had to re-create my user since it was crashing, so this is the new token that was generated after the user was re-created in the system.

**Comment by raghavneesh** [comment]
We need to reproduce it. Try login it many times & also try setting your system date for after 7 days.
I'll try to see at my end.

**Comment by fraggerfox** [comment]
Alright, I shall let you know, if it re-occurs.

**Comment by raghavneesh** [comment]
The same request is working with me.. Can you please also check with git
diff whether there is any change at your side.. Because if this is syntax
error then there has to be some wrong character..

**Comment by fraggerfox** [comment]
I think this is the wrong thread, the reply should go here https://github.com/raghavneesh/hh-appserver/issues/5

**Comment by fraggerfox** [comment]
Could not replicate the issue, closing the ticket.
