### ISSUE TITLE
Duplicate talks created on multiple posts

### ISSUE THREAD

**Issue by fraggerfox** [raghavneesh/hh-appserver#9]
#### Description of the Issue:

When multiple POSTs are done to `/users/talk/add` with the same data, the entries are duplicated at the server end.
#### Steps to reproduce:

POST the same JSON string multiple times to the server.
#### Expected behavior:

Every time a POST for adding in a set of talks comes in you will need to either
1. Check for duplicates and then update existing talks or add new talk if it does not exist.
2. Remove all the existing talks and add the new list that just came in.

Approach 2 is recommended, since every time the user wants to add talks they do it all in one bulk go when the "Next" button in the screen is pressed.

**Comment by raghavneesh** [comment]
Don't you think the flow should be like as follows:
1. Client tries to fetch all or some of user talk. Show it to user any
exists otherwise show button to add talk.
2. User can add multiple talks & you get the response of created tasks &
shows the list to user.
3. User then either edit or delete any created task.

In my opinion most of the apps approaches this problem like above. But if
we still want to do what you suggested then we will just check the
duplicates on the basis of timestamp. Will that work?

**Comment by fraggerfox** [comment]
Let me discuss this with @cherrymathew and get back to you.

**Comment by fraggerfox** [comment]
@cherrymathew , Could you update what was discussed in the call couple of weeks back? So that @raghavneesh can go ahead and implement the changes accordingly.

**Comment by cherrymathew** [comment]
Hi, 

I think we agreed on Approach 2, ie; the client edits _all_ talk data on page and pushes the data EN-MASSE to the server. The server needs to be able to identify the user/talk data structure and merge/overwrite/update it. 

This would address any consistency/duplication issues.

**Comment by cherrymathew** [comment]
@raghavneesh  - looks like there are duplicates still - any ETA on fixing this bug ? It clutters up the DB with redundant data .

**Comment by raghavneesh** [comment]
It should not be there.. I replace the whole object of user talks.

**Comment by cherrymathew** [comment]
> > > > > "Avneesh" == Avneesh Raghav notifications@github.com writes:

```
Avneesh> It should not be there.. I replace the whole object of user
Avneesh> talks.
```

Feel free to try it on the server we setup yesterday - it is up to date.

This is broken.

## 

Cherry

**Comment by fraggerfox** [comment]
Fixed in the latest commit and closing.
